services:
  database:
    image: postgres:latest
    container_name: ecommerce_db_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: ecommerce_backend_nestjs
    restart: always
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    volumes:
      - ./backend:/usr/app
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      NODE_ENV: ${NODE_ENV:-development}
      API_PORT: ${BACKEND_PORT:-3000}

  frontend:
    build: ./frontend
    container_name: ecommerce_frontend_react
    restart: always
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    volumes:
      - ./frontend:/usr/app
    stdin_open: true
    tty: true
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}

volumes:
  postgres_data:
